# Generated by Django 4.2.8 on 2025-09-30 02:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('serves', models.PositiveIntegerField(default=4, help_text='Default servings for this recipe')),
                ('image', models.ImageField(upload_to='recipes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('prep_time', models.PositiveIntegerField(default=10, help_text='Preparation time in minutes')),
                ('cook_time', models.PositiveIntegerField(default=10, help_text='Cooking time in minutes')),
                ('difficulty', models.CharField(default='Easy', max_length=20)),
                ('calories', models.IntegerField(default=0)),
                ('flame_level', models.CharField(default='Medium', max_length=20)),
                ('utensils', models.CharField(default='Frying Pan', max_length=100)),
                ('video_url', models.URLField(blank=True, default='')),
                ('cooking_steps', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(help_text='e.g., grams, cups, tsp', max_length=30)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_app.recipe_model')),
            ],
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('flame_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('utensil', models.CharField(default='Frying Pan', max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe_app.recipe_model')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='BeginnerGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooltip_text', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, default='')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe_model')),
            ],
        ),
    ]
