# Generated by Django 4.2.8 on 2025-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_alter_cookingstep_flame_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_model',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Salad', 'Salad'), ('Snack', 'Snack'), ('Other', 'Other')], default='Other', help_text='Classify this recipe by meal type', max_length=20),
        ),
    ]
